In [749]:
!pip install -U fortran-magic
%reload_ext fortranmagic

!pip install --upgrade pandas-datareader

import pandas_datareader as pdr
import datetime

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller
import matplotlib.pylab as plt
from matplotlib.pylab import rcParams

!pip install --upgrade quandl
!pip install yfinance
import yfinance as yf




%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [750]:
assert ran_the_first_cell, "Oh noes!"

In [751]:
#Ejemplo 1:

x = [234, 'gato', 3.1415, 4.245, 1238, "pero"]
x

[234, 'gato', 3.1415, 4.245, 1238, 'pero']

In [752]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [753]:
#Ejemplo 2:
primero = x[0]
segundo = x[1]
print("primero:", primero)
print("segundo:", segundo)


primero: 234
segundo: gato


In [754]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [755]:
#Ejemplo 3

ultimo = x[-1]
penultimo = x[-2]
print("ultimo:", ultimo)
print("penultimo:", penultimo)

ultimo: pero
penultimo: 1238


In [756]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [757]:
#Ejemplo 4
sublista = x[0:2]
sublista


[234, 'gato']

In [758]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [759]:
#Ejemplo 5
primero_tercero = x[:3]
primero_tercero


[234, 'gato', 3.1415]

In [760]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [761]:
#Ejemplo 6
despues_tres = x[3:]
despues_tres

[4.245, 1238, 'pero']

In [762]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [763]:
#Ejemplo 7
x = ['z', 'y', 'w', 'v', 'u', 'r', 's','t']
x[1:8:2]


['y', 'v', 'r', 't']

In [764]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [765]:
#Ejemplo 8
x[::-1]


['t', 's', 'r', 'u', 'v', 'w', 'y', 'z']

In [766]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [767]:
#Ejemplo 9

x = [2, 4, 6, 8, 10]
print("Antes:", x)
x.append('gato')
print("despues:", x)

Antes: [2, 4, 6, 8, 10]
despues: [2, 4, 6, 8, 10, 'gato']


In [768]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [769]:
#Ejemplo 10:

x = [2, 4, 6, 8, 10]
[y * 2 for y in x]

[4, 8, 12, 16, 20]

In [770]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [771]:
#Ejemplo 11:

Futbolistas = {'David': 'James', 'Falcao': 'García', 'Lionel': 'Messi'}
Futbolistas

{'David': 'James', 'Falcao': 'García', 'Lionel': 'Messi'}

In [772]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [773]:
#Ejemplo 11:
Futbolistas['Cristiano'] = 'Ronaldo'
Futbolistas


{'Cristiano': 'Ronaldo',
 'David': 'James',
 'Falcao': 'García',
 'Lionel': 'Messi'}

In [774]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

In [775]:
#Ejemplo 12:
del Futbolistas['David']
Futbolistas

{'Cristiano': 'Ronaldo', 'Falcao': 'García', 'Lionel': 'Messi'}

In [776]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [777]:
#Ejemplo 13:
x = [[2, 4, 6],
     [8, 10, 12],
     [14, 16, 18],
     [20, 22, 24]]

y = [[3, 5, 7, 9],
     [11, 13, 15, 17]]

In [778]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [779]:
#Ejemplo 14:
def matmul(X, Y):
    """Multiply matrix A by matrix B."""
    rows_out = len(X)
    cols_out = len(Y[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(T)):
                out[i][j] += X[i][k] * Y[k][j]
    return out



In [780]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [781]:
#ejemplo 15:

%%time
matmul(x, y)

CPU times: user 40 µs, sys: 1 µs, total: 41 µs
Wall time: 49.4 µs


[[50, 62, 74, 86],
 [134, 170, 206, 242],
 [218, 278, 338, 398],
 [302, 386, 470, 554]]

In [782]:
%%time

matmul(a, b)

CPU times: user 0 ns, sys: 41 µs, total: 41 µs
Wall time: 44.8 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [783]:
#ejemplo 16:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(3, 4)
randm

[[0.6803167492946278,
  0.9685151943120109,
  0.7578585222534989,
  0.8057067193169362],
 [0.7451312346669252,
  0.5899890955365178,
  0.2844991441639335,
  0.41344744761133423],
 [0.36743910729477003,
  0.17069901187699343,
  0.042997689303072906,
  0.047407418934977685]]

In [784]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.08702628172184801, 0.48831719754842273, 0.24218320100662316],
 [0.32811800914575273, 0.8709734438422644, 0.007407399439052997]]

In [785]:
#ejemplo 17
%%time
randx = random_matrix(500, 200)
randy = random_matrix(150, 450)
z = matmul(randx, randy)

CPU times: user 13.2 s, sys: 47.7 ms, total: 13.3 s
Wall time: 16.2 s


In [786]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 14.1 s, sys: 73.7 ms, total: 14.1 s
Wall time: 16.8 s


In [787]:
#ejemplo 18
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))


In [788]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [789]:
#ejemplo 19:

list_dato = [float(i) for i in range(50000)]
array_dato = np.array(list_dato)

In [790]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [791]:
#ejemplo 20:
%%time
python_dot_product(list_dato, list_dato)


CPU times: user 6.83 ms, sys: 0 ns, total: 6.83 ms
Wall time: 6.78 ms


41665416675000.0

In [792]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 11.1 ms, sys: 0 ns, total: 11.1 ms
Wall time: 11.7 ms


333328333350000.0

In [793]:
#ejemplo 21:
%%time
fortran_dot_product(array_dato, array_dato)

CPU times: user 139 µs, sys: 0 ns, total: 139 µs
Wall time: 144 µs


41665416675000.0

In [794]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 210 µs, sys: 0 ns, total: 210 µs
Wall time: 219 µs


333328333350000.0

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [795]:
#ejemplo 21:
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([2, 4, 6, 8], [1, 3 + 5j, 7.0, 'nueve'])

[2, (12+20j), 42.0, 'nuevenuevenuevenuevenuevenuevenuevenueve']

In [796]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [797]:
#ejemplo 23:
dato = np.array([2, 4, 6, 8])
dato


array([2, 4, 6, 8])

In [798]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [799]:
#ejemplo 24:
dato + dato

array([ 4,  8, 12, 16])

In [800]:
data + data

array([2, 4, 6, 8])

In [801]:
#ejemplo 25:

%%time
(array_dato * array_dato).sum()

CPU times: user 440 µs, sys: 16 µs, total: 456 µs
Wall time: 467 µs


41665416675000.0

In [802]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 673 µs, sys: 0 ns, total: 673 µs
Wall time: 865 µs


333328333350000.0

In [803]:
#ejemplo 26:
array_dato.dot(array_dato)


41665416675000.0

In [804]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 0 ns, sys: 254 µs, total: 254 µs
Wall time: 135 µs


333328333350000.0

In [805]:
#ejemplo 27:
%%time
fortran_dot_product(array_dato, array_dato)

CPU times: user 105 µs, sys: 0 ns, total: 105 µs
Wall time: 111 µs


41665416675000.0

In [806]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 192 µs, sys: 7 µs, total: 199 µs
Wall time: 209 µs


333328333350000.0

In [807]:
#ejemplo 28:

dos_por_dos = dato.reshape(2, 2)
dos_por_dos

array([[2, 4],
       [6, 8]])

In [808]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [809]:
#ejemplo 29:

arr = np.array([44, 223, 543, 411, 555, 126], dtype='int16').reshape(3, 2)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[ 44 223]
 [543 411]
 [555 126]]
DType: int16
Shape: (3, 2)
Strides: (4, 2)
Data: b',\x00\xdf\x00\x1f\x02\x9b\x01+\x02~\x00'


In [810]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [811]:
#ejemplo 30:
dato = np.arange(25).reshape(5, 5)
dato

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [812]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [813]:
#ejemplo 31:
dato*dato

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [814]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [815]:
#ejemplo 32: 

np.sqrt(dato)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

In [816]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [817]:
#ejemplo 33:
(dato % 5) == 0

array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False]])

In [818]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [819]:
#ejemplo 34:
((dato % 2) == 0) & ((dato % 5) == 0)

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

In [820]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [821]:
#ejemplo 35:
dato @ dato.T


array([[  30,   80,  130,  180,  230],
       [  80,  255,  430,  605,  780],
       [ 130,  430,  730, 1030, 1330],
       [ 180,  605, 1030, 1455, 1880],
       [ 230,  780, 1330, 1880, 2430]])

In [822]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [823]:
#ejemplo 36:
senos = np.sin(np.linspace(0, 2.13, 12))
cosenos = np.cos(np.linspace(0, 2.13, 12))
senos

array([0.        , 0.19242856, 0.37766453, 0.54878413, 0.69939127,
       0.82385653, 0.91752766, 0.97690342, 0.99976445, 0.98525625,
       0.93392111, 0.84767784])

In [824]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [825]:
#ejemplo 37:
senos[0]

0.0

In [826]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

In [827]:
#ejemplo 38:
senos[:3]

array([0.        , 0.19242856, 0.37766453])

In [828]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

In [829]:
#ejemplo 39:
senos[5:]

array([0.82385653, 0.91752766, 0.97690342, 0.99976445, 0.98525625,
       0.93392111, 0.84767784])

In [830]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [831]:
#ejemplo 40:
senos[::2]

array([0.        , 0.37766453, 0.69939127, 0.91752766, 0.99976445,
       0.93392111])

In [832]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [833]:
#ejemplo 41:
print("sines:\n", senos)
print("sines > 0.5:\n", senos > 0.5)
print("sines[sines > 0.5]:\n", senos[senos > 0.5])


sines:
 [0.         0.19242856 0.37766453 0.54878413 0.69939127 0.82385653
 0.91752766 0.97690342 0.99976445 0.98525625 0.93392111 0.84767784]
sines > 0.5:
 [False False False  True  True  True  True  True  True  True  True  True]
sines[sines > 0.5]:
 [0.54878413 0.69939127 0.82385653 0.91752766 0.97690342 0.99976445
 0.98525625 0.93392111 0.84767784]


In [834]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [835]:
#ejemplo 42: 
print(senos)
senos[[0, 2, 6]]

[0.         0.19242856 0.37766453 0.54878413 0.69939127 0.82385653
 0.91752766 0.97690342 0.99976445 0.98525625 0.93392111 0.84767784]


array([0.        , 0.37766453, 0.91752766])

In [836]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [837]:
#ejemplo 43:
unsorted_dato = np.array([112, 3123, 234, 11232, -121, 551, -2])

In [838]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [839]:
#ejemplo 44:
sort_indice = np.argsort(unsorted_dato)
sort_indice

array([4, 6, 0, 2, 5, 1, 3])

In [840]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [841]:
#ejemplo 45:
unsorted_dato[sort_indice]

array([ -121,    -2,   112,   234,   551,  3123, 11232])

In [842]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [843]:
#ejemplo 46:

market_capos = np.array([1122, 641, 1150, 523,116]) 
assets = np.array(['D', 'R', 'S', 'H', 'E'])

In [844]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [845]:
#EJEMPLO 47:
sort_by_mcapo = np.argsort(market_capos)
assets[sort_by_mcapo]


array(['E', 'D', 'B', 'A', 'C'], dtype='<U1')

In [846]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

On multi-dimensional arrays, we can slice along each axis independently.

In [847]:
#ejemplo 48:
dato = np.arange(36).reshape(6, 6)
dato

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [848]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [849]:
#ejemplo 49:

dato[:2, :2]

array([[0, 1],
       [6, 7]])

In [850]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

In [851]:
#ejemplo 50:
dato[:2, [0, -1]]

array([[ 0,  5],
       [ 6, 11]])

In [852]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [853]:
#ejemplo 51:
dato[(dato[:, 0] % 2) == 0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [854]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [855]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [856]:
#ejemplo 52:
variance(np.random.standard_normal(2500))

1.0194869572755532

In [857]:
variance(np.random.standard_normal(1000))

0.9964652990607551

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [858]:
#ejemplo 53:
dato = np.arange(145)
dato.mean()

72.0

In [859]:
data = np.arange(30)
data.mean()

14.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [860]:
#ejemplo 54:
dato = np.arange(45).reshape(3, 15)
dato

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [861]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [862]:
#ejemplo 55:
dato.mean()


22.0

In [863]:
data.mean()

14.5

In [864]:
#ejemplo 56:
dato.mean(axis=0)

array([15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
       28., 29.])

In [865]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [866]:
#ejemplo 57: 
dato.mean(axis=1)

array([ 7., 22., 37.])

In [867]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [868]:
#ejemplo 58:
fila = np.array([2, 42, 2353, 654])
columna = np.array([[341], [224], [323]])
print("fila:\n", fila, sep='')
print("columna:\n", columna, sep='')

fila:
[   2   42 2353  654]
columna:
[[341]
 [224]
 [323]]


In [869]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [870]:
#ejemplo 59:
fila + columna

array([[ 343,  383, 2694,  995],
       [ 226,  266, 2577,  878],
       [ 325,  365, 2676,  977]])

In [871]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [872]:
#ejemplo 60:

print("Data:\n", dato, sep='')
print("Mean:\n", dato.mean(axis=0), sep='')
print("Data - Mean:\n", dato - dato.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]]
Mean:
[15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
Data - Mean:
[[-15. -15. -15. -15. -15. -15. -15. -15. -15. -15. -15. -15. -15. -15.
  -15.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [ 15.  15.  15.  15.  15.  15.  15.  15.  15.  15.  15.  15.  15.  15.
   15.]]


In [873]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [874]:
#ejemplo 61:
x = pd.Series(index=['r', 's', 't', 'v', 'b'], data=[1231, 232, 3164, 154, 515])
x

r    1231
s     232
t    3164
v     154
b     515
dtype: int64

In [875]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [876]:
#ejemplo 62:
print("The index is:", x.index)
print("The values are:", x.values)

The index is: Index(['r', 's', 't', 'v', 'b'], dtype='object')
The values are: [1231  232 3164  154  515]


In [877]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [878]:
#ejemplo 63:
x.iloc[0]

1231

In [879]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [880]:
#ejemplo 64:
x.loc['r']

1231

In [881]:
# ... or by label.
s.loc['a']

1

In [882]:
#ejemplo 65:
x.iloc[:2]

r    1231
s     232
dtype: int64

In [883]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [884]:
#ejemplo 66:
x.loc[:'v']

r    1231
s     232
t    3164
v     154
dtype: int64

In [885]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [886]:
#ejemplo 67:
x.iloc[[0, -1]]

r    1231
b     515
dtype: int64

In [887]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [888]:
#ejemplo 68:
x.loc[x > 144]

r    1231
s     232
t    3164
v     154
b     515
dtype: int64

In [889]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [890]:
#ejemplo 69:
other_x = pd.Series({'a': 124, 'c': 2016.0, 'd': 13530.0, 'z': 40.450})
other_x

a      124.00
c     2016.00
d    13530.00
z       40.45
dtype: float64

In [891]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [892]:
#ejemplo 70:
x + other_x

a   NaN
b   NaN
c   NaN
d   NaN
r   NaN
s   NaN
t   NaN
v   NaN
z   NaN
dtype: float64

In [893]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [894]:
#ejemplo 71:
(x + other_x).fillna(0.0)

a    0.0
b    0.0
c    0.0
d    0.0
r    0.0
s    0.0
t    0.0
v    0.0
z    0.0
dtype: float64

In [895]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!